language: scala
branches:
  only:
    - master
sudo: required
services:
- docker
script:
- docker-compose run website grunt deploy
env:
  global:
  - secure: 6A/5bJjtu93HKivoonpLmRBDKyVp6ggoYC/d4YZqKTyU0/T34Q5Gto//coxMbn//gmeOfgpFeKeakQ8zrN6T50549Zy01e5wzJr7PtTc8ni94/hCphfslolA3YMAUyMV+auNTpOEtSj2x4okBDj4HkjVs9avNbREt21Wb4NO36FHvzzyu+lLoU+EEXQRNpJJzkRkYLfFOy/W+MT/VonnZbvNtQ0EXno0mOzrkjpVxH1B1w2BWLzWFM0HXvdwlF8yLf2HdHSw1R83z5FtX7pdxXW0/7kitHyjpOSHuJxX/bTOGTpiAPj8+sU3cDs1ZUdVJDQOzenOuNlJTqJ02RooMO5hl31cWbWWl61iDo5ZbAeHP90ysjVcaea61jB4+JvT6+rQjDDitGVM9hsWB/2qScTMBX6ZN3tx6drqkN6ep2qORLtZGryOZUcm+ej418sPt4ALP4xErTUKMwbPPAyMqlLKYkNcP2U3YweXJf88o8aZlFUAFj1XORXACidZS+PjG1Clal4uU+Ajkz83zJrxN+UJaDTQdqaMf+PX5TGfYUHhP2cVXJZx+gH2NS8dwfsLw8doVghM7J71tbIT3M+aDd9j9kpLA1qjGPn9vhgqQtf5qKkdV0xJpRExDkLGRme2Z827hvlp3LxfuUvTQH+eTayGl9RvMiFegd+3ilZHgm8=
  - secure: QKJ48Khjbpy0hqYTVNe2gXNMy799ljBPQJJz2p4cAYHby29BlwlyY/Ss5fSEFfMUvJEaMiS5sqtMMtMArAQinO8AuNzZxXOwNBJ9m5+8JEYBNLRCEgKALTGTdm+YAf8Im2VQbu/WMp1EB1D7lA2d/nMFXy6X1vlERRdCPkoVkeK/L0oQl6OAfS18qyMB/anzW+5JzYLsbRamgiAndjvxCA36YMFcmQXRwblRvKs/IjoxReXV5f7XBZ2fMqvWpYUVhBN4pt3n5l4j/APH/tFXFKYTNY+ovmziCKEFXIOnxveHfRSio5CN1rb++tZrYJlvRKARV+Dae1E3lUE52ZzhYLhy/9aZuN8ULwu4kGTnNtu8tnk9lt32figQkiCHnqGX3Q4BObrPxfLS2r3eFEt1Q/ySZjOS+UUZyGRATWeGOzuiVROqwRi3GwmXilo1OqdG+mEqbAF9Vx2qXy0HjFxj5UwpZfYGz7klkJ1RhKzLs4ZHV06yVK8oTHxR2Vv8CvEWrsdkzilhCwZSe3ibAFoeayddweRwL/W8ouQqplrk2pkV0eJC+FcxXtQtLUMQ6V71phOCW+iTVTL4A0x8YLcphPQ5kQxhytv6g/ik8VimSUzA2cu7p2CKC8FhJUatrRm4ejTDqxoS34CfNdr8OHi23iujy9ocrrPJtgVzdrpFMlY=
