# Jekyll Configuration
# --------------------

name                  : Underscore
description           : "Underscore: The Scala Consultancy"
url                   : "http://underscore.io"

source                : src/html
posts                 : _posts
layouts               : _layouts
includes              : _includes

destination           : underscoreio
plugins               : jekyll_plugins

keep_files            : [ 'css', 'js', 'images', 'fonts', 'vendor' ]

permalink             : /blog/posts/:year/:month/:day/:title.html
paginate              : 5
paginate_path         : "blog/page:num/"
excerpt_separator     : "<!-- break -->"

safe                  : false
highlighter           : pygments

collections:
  books:
    output: true
    permalink: /books/:path/
    layout: default
  courses:
    output: true
    permalink: /training/courses/:path/
    layout: default
  caseStudies:
    output: true
    permalink: /consulting/case-studies/:path/
    layout: default
  events:
    output: true
    layout: event
  jobs:
    output: true
    layout: job
    permalink: /jobs/:path/
