# Jekyll Configuration
# --------------------

name         : Underscore
description  : 'Underscore: The Scala Consultancy'
url          : http://underscore.io

source       : src/html
posts        : _posts
layouts      : _layouts
includes     : _includes

destination  : underscoreio
plugins      : jekyll_plugins

keep_files   : [ 'css', 'js', 'images', 'fonts' ]

permalink    : /blog/posts/:year/:month/:day/:title.html

safe         : false
highlighter  : pygments
markdown     : kramdown
markdown_ext : md

collections:
  courses:
    output: true
    permalink: /training/courses/:path/
    layout: default

kramdown:
  parse_block_html: true
