version: 2
jobs:
  build-and-deploy-if-master:
    working_directory: ~/underscoreio/underscoreio
    docker:
    - image: underscoreio/web-s3:latest
    steps:
    - checkout
    - run: bundle install

    - run:
        command: bundle exec rake test
        filters:
          branches:
            ignore: master

    - run:
        command: bundle exec rake deploy-production
        filters:
          branches:
            only: master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-deploy-if-master
  daily:
   triggers:
     - schedule:
         cron: "0 8 * * *"
         filters:
           branches:
             only:
               - master
   jobs:
     - build-and-deploy-if-master

