version: 2
jobs:
  build:
    working_directory: ~/underscoreio/underscoreio
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run:
        working_directory: ~/underscoreio/underscoreio
        command: 'echo ''Europe/London'' | sudo tee -a /etc/timezone; sudo dpkg-reconfigure
          -f noninteractive tzdata;'
    - run:
        working_directory: ~/underscoreio/underscoreio
        command: nvm install v5.7.0 && nvm alias default v5.7.0

    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-

    - run: npm install -g yarn
    - run: yarn
    - run: bundle install
    - run: sudo pip install awscli

    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.bundle
        - ~/.cache/bower
        - ./node_modules

    - run: bundle exec rake test

    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results

    - run: bundle exec rake deploy-production

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build


