version: 2
jobs:
  test-build:
    working_directory: ~/underscoreio/underscoreio
    docker:
    - image: underscoreio/web-s3:latest
    steps:
    - checkout
    - run: bundle install
    - run: bundle exec rake test

  deploy:
    working_directory: ~/underscoreio/underscoreio
    docker:
    - image: underscoreio/web-s3:latest
    steps:
    - run: apt-get update
    - run: apt-get install -y --no-install-recommends default-jre
    - checkout
    - run: bundle install
    - run: bundle exec rake deploy-production

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
      - test-build:
          filters:
              branches:
                ignore: master
  daily:
   triggers:
     - schedule:
         cron: "0 8 * * *"
         filters:
           branches:
             only:
               - master
   jobs:
     - deploy

